<?php

/**
 * @file
 * Contains entity_serial.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\Core\Entity\EntityInterface;
use Drupal\Core\Entity\ContentEntityInterface;

/**
 * Implements hook_help().
 */
function entity_serial_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the entity_serial module.
    case 'help.page.entity_serial':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Per bundle computed serial number.') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_entity_insert().
 *
 * Logs history of entities, to keep track of deleted ones
 * and provide consistent serial id calculation.
 */
function entity_serial_entity_insert(EntityInterface $entity) {
  if ($entity instanceof ContentEntityInterface) {
    $fields = [
      'entity_id' => $entity->id(),
      'entity_type_id' => $entity->getEntityTypeId(),
      'entity_bundle' => $entity->bundle(),
      'timestamp' => \Drupal::time()->getRequestTime(),
    ];
    try {
      \Drupal::database()->insert('entity_serial')
        ->fields($fields)
        ->execute();
    }
    catch (\Exception $exception) {
      \Drupal::messenger()->addError($exception->getMessage());
      \Drupal::logger('entity_serial')->error($exception->getMessage());
    }
  }
}
